Added webhook-certs volume mount to sidecar injector
hashicorp/vault-helm pull request #545
Opened 2021-06-04 12:28 UTC by rmgpinto

This PR adds the `webhook-certs` volume mount to sidecar injector.
Without it, the agent injector can't access the TLS certificate files.

2021-06-04 12:28 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault-helm?pullRequest=545)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault-helm?pullRequest=545)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault-helm?pullRequest=545).</sub>

2021-06-09 10:46 UTC, rmgpinto commented
@tvoran or @tomhjp ?

2021-06-10 00:59 UTC, tvoran requested changes
Good catch!

Can you also remove the volumeMount block from lines 170-173? It doesn't belong in the leader-elector container, and with injector.replicas=1 two volumeMount blocks will be rendered.

Would you also mind updating the [bats test](https://github.com/hashicorp/vault-helm/blob/5f2e1d470fc1f04972232f90c43883873bae0485/test/unit/injector-deployment.bats#L126-L126) to check for the webhook-certs mount? This test is an example: https://github.com/hashicorp/vault-helm/blob/030d3cd89db0e6d99ba5038bd12e2d0153112586/test/unit/csi-daemonset.bats#L283-L303

2021-06-10 22:31 UTC, tvoran approved these changes
Thanks!

2021-06-10 22:32 UTC, merged