Allow additional annotations for standby and active services via config
hashicorp/vault-helm pull request #896
Opened 2023-05-19 10:32 UTC by tekicat

Revival of https://github.com/hashicorp/vault-helm/pull/546

Currently there is no ability to annotate services for active and standby services, as they inherit their settings from the main server service configuration. This is a problem,  when you need to attach different annotations to the different services. Instead of just allowing for setting of annotations, I opted to allow configuring the services for more flexibility.

Thanks @jamesgoodhouse

2023-05-19 10:32 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault-helm?pullRequest=896)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault-helm?pullRequest=896)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault-helm?pullRequest=896).</sub>

2023-09-18 03:50 UTC, chris-ng-scmp commented
This is a must have feature for Vault HELM chart to set difference annotations for individual services, how long we can see this appoved?

2023-09-25 18:42 UTC, kschoche requested changes
Hi @tekicat -
Thanks for submitting this, I just got around to reviewing. I think the approach looks good, and is a nice+clean iteration of the original PR.
I left a few suggestions about missing tests, and some general cleanup, and after these get addressed I think we're good to go!
Let me know if you have any questions about any the feedback.
~Kyle

2023-09-25 18:42 UTC, kschoche commented on templates/_helpers.tpl
> +
I was going to suggest that we dry this up a bit and make it a single function where we just pass in `.Values.server.service.active/standby` as the root, but I ran into https://github.com/helm/helm/issues/5979 trying to implement it myself, so I think it's okay as is.

2023-09-25 18:42 UTC, kschoche commented on templates/server-ha-active-service.yaml
>  {{ template "vault.service.annotations" .}}
Clean up some extra whitespace when templating:
```suggestion
{{- template "vault.service.active.annotations" . }}
{{- template "vault.service.annotations" . }}
```

2023-09-25 18:42 UTC, kschoche commented on templates/server-ha-standby-service.yaml
>  {{ template "vault.service.annotations" .}}
```suggestion
{{- template "vault.service.standby.annotations" . }}
{{- template "vault.service.annotations" . }}
```

2023-09-25 18:42 UTC, kschoche commented on test/unit/server-ha-active-service.bats
> +
```suggestion
@test "server/ha-active-Service: with both annotations set" {
  cd `chart_dir`
  local object=$(helm template \
      --show-only templates/server-ha-active-service.yaml \
      --set 'server.ha.enabled=true' \
      --set 'server.service.active.annotations=vaultIsAwesome: true' \
      --set 'server.service.annotations=vaultIsNotAwesome: false' \
      . | tee /dev/stderr |
      yq -r '.metadata' | tee /dev/stderr)

  local actual=$(echo "$object" | yq '.annotations["vaultIsAwesome"]' | tee /dev/stderr)
  [ "${actual}" = "true" ]
  actual=$(echo "$object" | yq '.annotations["vaultIsNotAwesome"]' | tee /dev/stderr)
  [ "${actual}" = "false" ]
}
```

2023-09-25 18:42 UTC, kschoche commented on test/unit/server-ha-standby-service.bats
> +
Adding a test that uses both annotations:

```suggestion
@test "server/ha-standby-Service: with both annotations set" {
  cd `chart_dir`
  local object=$(helm template \
      --show-only templates/server-ha-standby-service.yaml \
      --set 'server.ha.enabled=true' \
      --set 'server.service.standby.annotations=vaultIsAwesome: true' \
      --set 'server.service.annotations=vaultIsNotAwesome: false' \
      . | tee /dev/stderr |
      yq -r '.metadata' | tee /dev/stderr)

  local actual=$(echo "$object" | yq '.annotations["vaultIsAwesome"]' | tee /dev/stderr)
  [ "${actual}" = "true" ]
  actual=$(echo "$object" | yq '.annotations["vaultIsNotAwesome"]' | tee /dev/stderr)
  [ "${actual}" = "false" ]
}
```

2023-09-26 19:00 UTC, tekicat commented
Thanks for the suggestions @kschoche , they looked good and I have applied them. :)

2023-09-26 20:28 UTC, kschoche approved these changes
Thanks so much, this looks great!

2023-09-26 20:28 UTC, merged